# Generated by Django 3.0.5 on 2020-04-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(blank=True, max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_task', to='project.Task')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Name')),
                ('doc', models.FileField(blank=True, upload_to='', verbose_name='document')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('check_result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('EMPTY', 'Empty')], default='EMPTY', max_length=5)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='document.Document')),
            ],
        ),
    ]
